### ISSUE TITLE
How to do "redactions" in auto_assert result values?

### ISSUE THREAD

**Issue by arunaugustine** [zachallaun/mneme#49]
I'm trying to figure out how to do "redactions", similar to [this feature in insta.rs](https://insta.rs/docs/redactions/). From the docs and examples, it was not clear on how to do this. 

Basically I am trying to get the auto_assert to pass even if a string value in the result varies slightly (for e.g generated uuid number).

**Comment by zachallaun** [comment]
Thank you for reaching out!

Mneme does not currently support automatic redactions, but there are a couple techniques you can use depending on where the random value appears. 

1. In a composite data structure, like a map/tuple/struct, you can modify the generated pattern to use a "wildcard". 

```elixir
# generated assertion
auto_assert %{uuid: "12345", ...} <- do_thing()

# edit the pattern to be:
auto_assert %{uuid: _, ...} <- do_thing()
# or:
auto_assert %{uuid: uuid, ...} when is_binary(uuid) <- do_thing()
```

Either of these will pass the next time your tests run, because Mneme uses pattern matching under the hood (extended with guards). 

2. For strings, write a simple utility to "sanitize" the output. 

```elixir
auto_assert "XXXX-... etc." <- do_thing() |> sanitize()

...

defp sanitize(s) do
  String.replace(...)
end
```

This is similar to Insta's "filters" feature, though less automated. 

---

Would one of these apply to your use case?

I can think of a few ways that Mneme could be improved in this regard, but I want to make sure that further added features are necessary and fully-baked. I'll continue thinking on it.

**Comment by arunaugustine** [comment]
That makes sense! And it works well for my use case! 

Thank you for the fast reply!
